#parte 1
bin/dia8_parte1: dia8_parte1.cpp
	mkdir -p bin
	g++ -o bin/dia8_parte1 dia8_parte1.cpp

#parte 2
bin/dia8_parte2: dia8_parte2.cpp
	mkdir -p bin
	g++ -o bin/dia8_parte2 dia8_parte2.cpp

clean:
	rm -rf *.o *.gch bin
