# Makefile para dia7_parte1_recursividad_y_DyV

bin/dia7_parte1_recursividad_y_DyV: dia7_parte1_recursividad_y_DyV.cpp
	mkdir -p bin
	g++ -std=c++17 -O2 -Wall -o bin/dia7_parte1_recursividad_y_DyV dia7_parte1_recursividad_y_DyV.cpp

clean:
	rm -rf *.o *.gch bin

