# Makefile para dia7_parte1_recursividad

bin/dia7_parte1_recursividad: dia7_parte1_recursividad.cpp
	mkdir -p bin
	g++ -std=c++17 -O2 -Wall -o bin/dia7_parte1_recursividad dia7_parte1_recursividad.cpp

clean:
	rm -rf *.o *.gch bin

