# Makefile para dia1_parte1_tabla_hash

bin/dia1_parte1_tabla_hash: dia1_parte1_tabla_hash.cpp
	mkdir -p bin
	g++ -std=c++17 -O2 -Wall -o bin/dia1_parte1_tabla_hash dia1_parte1_tabla_hash.cpp

bin/dia1_parte2_tabla_hash: dia1_parte2_tabla_hash.cpp
	mkdir -p bin
	g++ -std=c++17 -O2 -Wall -o bin/dia1_parte2_tabla_hash dia1_parte2_tabla_hash.cpp


clean:
	rm -rf *.o *.gch bin

